/**
 *   Copyright 2018 Pascal Ammon, Gabriel Wyss
 * 
 * 	 Implementation eines anonymen Mobility Pricing Systems auf Basis eines Gruppensignaturschemas
 * 
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * From the Join Request, the Server forms the Join Response.
 * This Response is then sent back to the future group member.
 * It then allows the member to calculate the final version of its 
 * Secret Key (Member Key).
 * wi is the element of the Secret Key the Server needs, in case 
 * he wants to revoke this Secret Key
 * yi is the main signing key, known to the Server, but not to the other members
 * Ei is the element, which identifies the member and can be published on the
 * CRL, so the other members can update their Public Key.
 * ri is a random number generated by the Server. The member then adds a random
 * number to it, that only he knows.
 * 
 */
package responses;

import java.math.BigInteger;

import com.google.gson.annotations.Expose;

public class JoinResponse {
	@Expose
	private final BigInteger wi;
	@Expose
	private final BigInteger yi;
	@Expose
	private final BigInteger Ei;
	@Expose
	private final BigInteger ri;
	@Expose
	private final BigInteger e;

	public JoinResponse(BigInteger wi, BigInteger yi, BigInteger Ei, BigInteger ri, BigInteger e) {
		this.wi = wi;
		this.yi = yi;
		this.Ei = Ei;
		this.ri = ri;
		this.e = e;

	}

	public BigInteger getE() {
		return e;
	}

	public BigInteger getWi() {
		return wi;
	}

	public BigInteger getYi() {
		return yi;
	}

	public BigInteger getEi() {
		return Ei;
	}

	public BigInteger getRi() {
		return ri;
	}

}
